export const DESTINATIONS = {
  1: [
    // Global
    {
      id: "maldives-jan",
      name: "Maldives",
      country: "Maldives",
      region: "Global",
      description:
        "January is peak season in the Maldives with crystal-clear skies and calm turquoise seas. Perfect conditions for snorkeling, diving, and overwater bungalow stays.",
      highlights: ["Overwater Bungalows", "Coral Reef Diving", "Whale Shark Snorkeling"],
      avgTempCelsius: 29,
      bestFor: "Beaches & Relaxation",
      imageEmoji: "🏝️",
      iataCode: "MLE",
    },
    {
      id: "bali-jan",
      name: "Bali",
      country: "Indonesia",
      region: "Global",
      description:
        "January's dry spell between monsoons makes Bali's terraced rice fields and temples magical. Ideal for surfing in Uluwatu and temple hopping.",
      highlights: ["Uluwatu Temple", "Tegallalang Rice Terraces", "Seminyak Beach"],
      avgTempCelsius: 27,
      bestFor: "Culture & Beaches",
      imageEmoji: "🌺",
      iataCode: "DPS",
    },
    {
      id: "morocco-jan",
      name: "Marrakech",
      country: "Morocco",
      region: "Global",
      description:
        "January offers cool, pleasant weather to explore Marrakech's souks and riads without the summer heat. The Atlas Mountains offer snowcapped backdrops.",
      highlights: ["Jemaa el-Fna Square", "Majorelle Garden", "Atlas Mountains Day Trip"],
      avgTempCelsius: 12,
      bestFor: "Culture & History",
      imageEmoji: "🕌",
      iataCode: "RAK",
    },
    // India
    {
      id: "goa-jan",
      name: "Goa",
      country: "India",
      region: "India",
      description:
        "January is Goa's golden month — sunny skies, buzzing beach shacks, and the famous New Year hangover lingers into a festive atmosphere all month.",
      highlights: ["Baga & Anjuna Beach", "Old Goa Churches", "Dudhsagar Waterfalls"],
      avgTempCelsius: 26,
      bestFor: "Beaches & Nightlife",
      imageEmoji: "🏖️",
      iataCode: "GOI",
    },
    {
      id: "jaipur-jan",
      name: "Jaipur",
      country: "India",
      region: "India",
      description:
        "The Pink City is at its best in January with mild temperatures perfect for exploring forts, palaces, and vibrant bazaars. The Jaipur Literature Festival is a highlight.",
      highlights: ["Amber Fort", "Hawa Mahal", "Jaipur Literature Festival"],
      avgTempCelsius: 16,
      bestFor: "Culture & History",
      imageEmoji: "🏰",
      iataCode: "JAI",
    },
    {
      id: "kerala-jan",
      name: "Kerala (Backwaters)",
      country: "India",
      region: "India",
      description:
        "January is ideal for Kerala's backwaters with clear skies and cool evenings. Houseboat cruises on Alleppey's canals are a once-in-a-lifetime experience.",
      highlights: ["Alleppey Houseboat", "Periyar Wildlife Sanctuary", "Kovalam Beach"],
      avgTempCelsius: 27,
      bestFor: "Nature & Wellness",
      imageEmoji: "🛶",
      iataCode: "COK",
    },
  ],

  2: [
    // Global
    {
      id: "thailand-feb",
      name: "Chiang Mai",
      country: "Thailand",
      region: "Global",
      description:
        "February is prime time in Northern Thailand before the hot season. The Flower Festival and cooler temperatures make Chiang Mai enchanting.",
      highlights: ["Doi Inthanon National Park", "Night Bazaar", "Elephant Sanctuary"],
      avgTempCelsius: 25,
      bestFor: "Culture & Nature",
      imageEmoji: "🐘",
      iataCode: "CNX",
    },
    {
      id: "newzealand-feb",
      name: "Queenstown",
      country: "New Zealand",
      region: "Global",
      description:
        "February is peak summer in New Zealand. Queenstown's adventure capital buzzes with hiking, bungee jumping, and stunning Fiordland scenery.",
      highlights: ["Milford Sound Cruise", "Bungee Jumping", "Routeburn Track"],
      avgTempCelsius: 22,
      bestFor: "Adventure & Nature",
      imageEmoji: "🏔️",
      iataCode: "ZQN",
    },
    {
      id: "peru-feb",
      name: "Machu Picchu",
      country: "Peru",
      region: "Global",
      description:
        "February sees fewer crowds at Machu Picchu. The rainy season keeps the ruins dramatically misty and the orchids in bloom along the Inca Trail.",
      highlights: ["Machu Picchu Citadel", "Inca Trail Trek", "Sacred Valley"],
      avgTempCelsius: 17,
      bestFor: "History & Adventure",
      imageEmoji: "🏛️",
      iataCode: "CUZ",
    },
    // India
    {
      id: "agra-feb",
      name: "Agra",
      country: "India",
      region: "India",
      description:
        "February's pleasant weather is perfect for visiting the Taj Mahal at sunrise. Clear skies make the marble monument glow a heavenly pink at dawn.",
      highlights: ["Taj Mahal Sunrise", "Agra Fort", "Fatehpur Sikri"],
      avgTempCelsius: 20,
      bestFor: "History & Romance",
      imageEmoji: "🕍",
      iataCode: "AGR",
    },
    {
      id: "hampi-feb",
      name: "Hampi",
      country: "India",
      region: "India",
      description:
        "February is ideal for exploring Hampi's surreal boulder-strewn landscape and Vijayanagara Empire ruins before the Karnataka summer heat sets in.",
      highlights: ["Virupaksha Temple", "Vittala Temple Chariot", "Tungabhadra River Coracles"],
      avgTempCelsius: 28,
      bestFor: "History & Adventure",
      imageEmoji: "🪨",
      iataCode: "HBX",
    },
    {
      id: "andaman-feb",
      name: "Andaman Islands",
      country: "India",
      region: "India",
      description:
        "February offers the best sea conditions around the Andamans. Crystal-clear visibility for scuba diving and calm waters for island hopping.",
      highlights: ["Radhanagar Beach", "Scuba Diving at Havelock", "Cellular Jail"],
      avgTempCelsius: 28,
      bestFor: "Beaches & Diving",
      imageEmoji: "🤿",
      iataCode: "IXZ",
    },
  ],

  3: [
    // Global
    {
      id: "japan-mar",
      name: "Kyoto",
      country: "Japan",
      region: "Global",
      description:
        "March brings the iconic cherry blossom season to Japan. Kyoto's ancient temples framed by sakura trees is one of the world's most breathtaking sights.",
      highlights: ["Arashiyama Bamboo Grove", "Fushimi Inari Shrine", "Cherry Blossom Hanami"],
      avgTempCelsius: 10,
      bestFor: "Culture & Cherry Blossoms",
      imageEmoji: "🌸",
      iataCode: "KIX",
    },
    {
      id: "iceland-mar",
      name: "Reykjavik",
      country: "Iceland",
      region: "Global",
      description:
        "March offers strong chances of Northern Lights with increasing daylight. The Snæfellsnes Peninsula and Golden Circle are dramatically beautiful.",
      highlights: ["Northern Lights", "Golden Circle", "Blue Lagoon"],
      avgTempCelsius: 2,
      bestFor: "Northern Lights & Nature",
      imageEmoji: "🌌",
      iataCode: "KEF",
    },
    {
      id: "portugal-mar",
      name: "Lisbon",
      country: "Portugal",
      region: "Global",
      description:
        "March is perfect shoulder season in Lisbon — mild weather, no crowds, and blooming almond trees. Explore Sintra's fairy-tale palaces at leisure.",
      highlights: ["Sintra Palaces", "Belém Tower", "Alfama District Fado"],
      avgTempCelsius: 15,
      bestFor: "Culture & Sightseeing",
      imageEmoji: "🏯",
      iataCode: "LIS",
    },
    // India
    {
      id: "mathura-mar",
      name: "Mathura (Holi)",
      country: "India",
      region: "India",
      description:
        "March is synonymous with Holi, and the birthplace of Lord Krishna celebrates it most magnificently. Experience Lathmar Holi in Barsana — a UNESCO-recognized tradition.",
      highlights: ["Lathmar Holi in Barsana", "Dwarkadheesh Temple", "Vrindavan Temples"],
      avgTempCelsius: 25,
      bestFor: "Festivals & Culture",
      imageEmoji: "🎨",
      iataCode: "AGR",
    },
    {
      id: "rishikesh-mar",
      name: "Rishikesh",
      country: "India",
      region: "India",
      description:
        "March sees the Ganga flowing strong and clear, perfect for white-water rafting. The International Yoga Festival draws thousands to the Yoga Capital of the World.",
      highlights: ["White Water Rafting", "International Yoga Festival", "Laxman Jhula"],
      avgTempCelsius: 20,
      bestFor: "Adventure & Wellness",
      imageEmoji: "🧘",
      iataCode: "DED",
    },
    {
      id: "munnar-mar",
      name: "Munnar",
      country: "India",
      region: "India",
      description:
        "March is magical in Munnar as neelakurinji wildflowers occasionally bloom and tea estates glow a vivid green before the pre-monsoon heat.",
      highlights: ["Tea Museum", "Eravikulam National Park", "Mattupetty Dam"],
      avgTempCelsius: 18,
      bestFor: "Nature & Tea Gardens",
      imageEmoji: "🍵",
      iataCode: "COK",
    },
  ],

  4: [
    // Global
    {
      id: "italy-apr",
      name: "Amalfi Coast",
      country: "Italy",
      region: "Global",
      description:
        "April brings spring bloom to the Amalfi Coast without peak summer crowds. Pastel-colored villages cling to dramatic cliffs above the azure Tyrrhenian Sea.",
      highlights: ["Positano Village", "Path of the Gods Hike", "Ravello Gardens"],
      avgTempCelsius: 17,
      bestFor: "Scenic Beauty & Food",
      imageEmoji: "🍋",
      iataCode: "NAP",
    },
    {
      id: "vietnam-apr",
      name: "Hoi An",
      country: "Vietnam",
      region: "Global",
      description:
        "April is ideal for Hoi An before the rainy season. The ancient lantern-lit town is perfect for tailors, cooking classes, and cycling through rice paddies.",
      highlights: ["Ancient Town Lantern Festival", "My Son Sanctuary", "Cooking Classes"],
      avgTempCelsius: 29,
      bestFor: "Culture & Food",
      imageEmoji: "🏮",
      iataCode: "DAD",
    },
    {
      id: "jordan-apr",
      name: "Petra",
      country: "Jordan",
      region: "Global",
      description:
        "April is the best month for Petra — comfortable temperatures and wildflowers blooming in Wadi Rum. The rose-red city glows magnificently at sunset.",
      highlights: ["The Treasury (Al-Khazneh)", "Wadi Rum Jeep Tour", "Little Petra"],
      avgTempCelsius: 21,
      bestFor: "History & Adventure",
      imageEmoji: "🏜️",
      iataCode: "AMM",
    },
    // India
    {
      id: "darjeeling-apr",
      name: "Darjeeling",
      country: "India",
      region: "India",
      description:
        "April is the second flush tea season in Darjeeling. Clear skies offer stunning views of Kangchenjunga and the Toy Train runs through flowering rhododendrons.",
      highlights: ["Tiger Hill Sunrise over Kangchenjunga", "Toy Train Ride", "Tea Estate Tour"],
      avgTempCelsius: 15,
      bestFor: "Nature & Tea Culture",
      imageEmoji: "🚂",
      iataCode: "IXB",
    },
    {
      id: "ooty-apr",
      name: "Ooty",
      country: "India",
      region: "India",
      description:
        "April in Ooty is pleasantly cool when the plains sizzle. The Nilgiris bloom with flowers and the Botanical Garden's annual flower show draws visitors from across India.",
      highlights: ["Botanical Garden Flower Show", "Nilgiri Mountain Railway", "Ooty Lake Boating"],
      avgTempCelsius: 16,
      bestFor: "Hill Stations & Nature",
      imageEmoji: "🌷",
      iataCode: "CJB",
    },
    {
      id: "coorg-apr",
      name: "Coorg",
      country: "India",
      region: "India",
      description:
        "April sees Coorg's coffee estates in full blossom. The air is thick with jasmine-like coffee flowers and the hills are a lush green before monsoon.",
      highlights: ["Abbey Falls", "Raja's Seat", "Kodava Coffee Estate Walk"],
      avgTempCelsius: 22,
      bestFor: "Nature & Coffee Estates",
      imageEmoji: "☕",
      iataCode: "IXM",
    },
  ],

  5: [
    // Global
    {
      id: "greece-may",
      name: "Santorini",
      country: "Greece",
      region: "Global",
      description:
        "May is arguably the best month in Santorini — perfect weather, fewer tourists than summer, and the caldera views are breathtaking. Ideal for island hopping.",
      highlights: ["Oia Sunset", "Akrotiri Ruins", "Caldera Boat Tour"],
      avgTempCelsius: 21,
      bestFor: "Romance & Scenery",
      imageEmoji: "⛵",
      iataCode: "JTR",
    },
    {
      id: "france-may",
      name: "Provence",
      country: "France",
      region: "Global",
      description:
        "May in Provence is magical — lavender fields begin blooming, markets overflow with fresh produce, and the weather is warm and sunny without summer heat.",
      highlights: ["Lavender Fields of Valensole", "Gorges du Verdon", "Aix-en-Provence Markets"],
      avgTempCelsius: 20,
      bestFor: "Countryside & Food",
      imageEmoji: "💜",
      iataCode: "MRS",
    },
    {
      id: "croatia-may",
      name: "Dubrovnik",
      country: "Croatia",
      region: "Global",
      description:
        "May is perfect for Dubrovnik before the peak summer crowds. Walk the ancient city walls, kayak sea caves, and island-hop in the Adriatic before prices spike.",
      highlights: ["Old City Walls Walk", "Lokrum Island", "Elafiti Islands Kayaking"],
      avgTempCelsius: 20,
      bestFor: "History & Beaches",
      imageEmoji: "🏰",
      iataCode: "DBV",
    },
    // India
    {
      id: "leh-may",
      name: "Leh-Ladakh",
      country: "India",
      region: "India",
      description:
        "May marks the opening of Ladakh after winter. Roads reopen, monasteries come alive with festivals, and the high-altitude desert landscape is spectacular with snowcapped peaks.",
      highlights: ["Pangong Tso Lake", "Nubra Valley Camels", "Thiksey Monastery"],
      avgTempCelsius: 14,
      bestFor: "Adventure & Monasteries",
      imageEmoji: "🏔️",
      iataCode: "IXL",
    },
    {
      id: "spiti-may",
      name: "Spiti Valley",
      country: "India",
      region: "India",
      description:
        "May is when Spiti Valley awakens from its winter slumber. The high-altitude desert is accessible, Key Monastery hosts sacred festivals, and the Himalayan scenery is surreal.",
      highlights: ["Key Monastery", "Chandratal Lake", "Dhankar Lake Trek"],
      avgTempCelsius: 10,
      bestFor: "Remote Adventure & Monasteries",
      imageEmoji: "🗻",
      iataCode: "KUU",
    },
    {
      id: "manali-may",
      name: "Manali",
      country: "India",
      region: "India",
      description:
        "May in Manali offers snow adventures on Rohtang Pass before the monsoon. Apple blossoms carpet the Kullu Valley and the air is fresh and crisp.",
      highlights: ["Rohtang Pass", "Solang Valley", "Hadimba Temple"],
      avgTempCelsius: 12,
      bestFor: "Snow Adventure & Nature",
      imageEmoji: "🍎",
      iataCode: "KUU",
    },
  ],

  6: [
    // Global
    {
      id: "scotland-jun",
      name: "Scottish Highlands",
      country: "United Kingdom",
      region: "Global",
      description:
        "June offers almost 18 hours of daylight in the Scottish Highlands. Purple heather begins blooming, whisky distilleries are in full swing, and the midges are manageable.",
      highlights: ["Loch Ness", "Isle of Skye", "Glencoe Valley"],
      avgTempCelsius: 14,
      bestFor: "Scenic Drives & Whisky",
      imageEmoji: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
      iataCode: "INV",
    },
    {
      id: "norway-jun",
      name: "Bergen (Fjords)",
      country: "Norway",
      region: "Global",
      description:
        "June is Midnight Sun season in Norway. The Sognefjord and Geirangerfjord are stunningly lit around the clock, perfect for fjord cruises and hiking.",
      highlights: ["Geirangerfjord Cruise", "Midnight Sun Experience", "Bergen Wharf (Bryggen)"],
      avgTempCelsius: 16,
      bestFor: "Fjords & Midnight Sun",
      imageEmoji: "🌄",
      iataCode: "BGO",
    },
    {
      id: "canada-jun",
      name: "Banff",
      country: "Canada",
      region: "Global",
      description:
        "June in Banff sees the Rocky Mountains at peak beauty — wildflowers carpet alpine meadows, turquoise glacial lakes emerge from ice, and wildlife is abundant.",
      highlights: ["Lake Louise", "Moraine Lake", "Icefields Parkway Drive"],
      avgTempCelsius: 13,
      bestFor: "Mountains & Wildlife",
      imageEmoji: "🦌",
      iataCode: "YYC",
    },
    // India
    {
      id: "meghalaya-jun",
      name: "Meghalaya",
      country: "India",
      region: "India",
      description:
        "June brings Meghalaya's living root bridges and waterfalls to life. Cherrapunji, one of the world's wettest places, transforms into a green paradise.",
      highlights: ["Living Root Bridges", "Nohkalikai Falls", "Mawlynnong Village"],
      avgTempCelsius: 20,
      bestFor: "Monsoon Magic & Nature",
      imageEmoji: "🌿",
      iataCode: "SHL",
    },
    {
      id: "sikkim-jun",
      name: "Sikkim",
      country: "India",
      region: "India",
      description:
        "June in Sikkim is verdant and beautiful before heavy rains set in. Rhododendron forests, Buddhist monasteries, and views of Kangchenjunga make it unforgettable.",
      highlights: ["Gurudongmar Lake", "Rumtek Monastery", "Yumthang Valley"],
      avgTempCelsius: 18,
      bestFor: "Mountains & Monasteries",
      imageEmoji: "🌺",
      iataCode: "PYG",
    },
    {
      id: "uttarakhand-jun",
      name: "Valley of Flowers",
      country: "India",
      region: "India",
      description:
        "June signals the opening of the Valley of Flowers trek in Uttarakhand. This UNESCO World Heritage meadow bursts with 300+ alpine flower species.",
      highlights: ["Valley of Flowers Trek", "Hemkund Sahib", "Badrinath Temple"],
      avgTempCelsius: 12,
      bestFor: "Trekking & Flowers",
      imageEmoji: "🌸",
      iataCode: "DED",
    },
  ],

  7: [
    // Global
    {
      id: "newzealand-jul",
      name: "Queenstown (Winter)",
      country: "New Zealand",
      region: "Global",
      description:
        "July is ski season in New Zealand's South Island. Queenstown and Wanaka offer world-class skiing with stunning alpine scenery and vibrant après-ski culture.",
      highlights: ["Coronet Peak Skiing", "Treble Cone Snowboarding", "Wanaka Winter Festival"],
      avgTempCelsius: 5,
      bestFor: "Skiing & Winter Sports",
      imageEmoji: "⛷️",
      iataCode: "ZQN",
    },
    {
      id: "southafrica-jul",
      name: "Cape Town",
      country: "South Africa",
      region: "Global",
      description:
        "July in Cape Town is whale watching season. Southern Right Whales nurse calves in Walker Bay, while the city enjoys crisp winter days perfect for wine routes.",
      highlights: ["Whale Watching in Hermanus", "Table Mountain", "Cape Winelands"],
      avgTempCelsius: 12,
      bestFor: "Wildlife & Scenery",
      imageEmoji: "🐋",
      iataCode: "CPT",
    },
    {
      id: "peru-jul",
      name: "Amazon Rainforest",
      country: "Peru",
      region: "Global",
      description:
        "July is dry season in the Peruvian Amazon, making jungle lodges accessible. Wildlife concentrates near water sources, offering exceptional wildlife spotting.",
      highlights: ["Amazon River Cruise", "Pink River Dolphin Sighting", "Canopy Walkways"],
      avgTempCelsius: 28,
      bestFor: "Wildlife & Jungle",
      imageEmoji: "🐍",
      iataCode: "IQT",
    },
    // India
    {
      id: "munnar-jul",
      name: "Munnar (Monsoon)",
      country: "India",
      region: "India",
      description:
        "July transforms Munnar into a cloud-wrapped emerald paradise. Tea estates glow vivid green, waterfalls cascade dramatically, and the misty hills offer a magical escape.",
      highlights: ["Attukad Waterfalls", "Blossom Park", "Tea Estate Walks in Mist"],
      avgTempCelsius: 17,
      bestFor: "Monsoon Greenery & Tea",
      imageEmoji: "🌧️",
      iataCode: "COK",
    },
    {
      id: "coorg-jul",
      name: "Coorg (Monsoon)",
      country: "India",
      region: "India",
      description:
        "July in Coorg is lush and dramatic — waterfalls thunder through coffee and pepper estates, leeches aside, the landscape is emerald and atmospheric.",
      highlights: ["Iruppu Falls", "Nagarhole National Park", "Monsoon Spa Retreats"],
      avgTempCelsius: 20,
      bestFor: "Monsoon Retreats & Nature",
      imageEmoji: "☔",
      iataCode: "IXM",
    },
    {
      id: "andaman-jul",
      name: "Andaman Islands (South)",
      country: "India",
      region: "India",
      description:
        "July's southwest monsoon misses the southern Andaman Islands, so Neil and Havelock remain calm. Excellent for snorkeling and beach walks without crowds.",
      highlights: ["Neil Island Beaches", "Bharatpur Beach Snorkeling", "Sunrise at Radhanagar"],
      avgTempCelsius: 29,
      bestFor: "Beaches & Snorkeling",
      imageEmoji: "🐠",
      iataCode: "IXZ",
    },
  ],

  8: [
    // Global
    {
      id: "iceland-aug",
      name: "Iceland (Summer)",
      country: "Iceland",
      region: "Global",
      description:
        "August is Iceland's warmest month. Puffins nest on the Westfjords, the Highlands are accessible, and the Midnight Sun is still visible. Perfect for camping.",
      highlights: ["Landmannalaugar Highlands", "Puffin Watching", "Jökulsárlón Glacier Lagoon"],
      avgTempCelsius: 11,
      bestFor: "Nature & Midnight Sun",
      imageEmoji: "🐦",
      iataCode: "KEF",
    },
    {
      id: "switzerland-aug",
      name: "Interlaken",
      country: "Switzerland",
      region: "Global",
      description:
        "August is peak summer in the Swiss Alps. Alpine meadows are in full bloom, paragliding over Thun Lake is exhilarating, and the Jungfrau railway offers stunning vistas.",
      highlights: ["Jungfraujoch (Top of Europe)", "Paragliding over Thun Lake", "Lauterbrunnen Valley"],
      avgTempCelsius: 19,
      bestFor: "Adventure & Alpine Scenery",
      imageEmoji: "🏔️",
      iataCode: "ZRH",
    },
    {
      id: "morocco-aug",
      name: "Fès",
      country: "Morocco",
      region: "Global",
      description:
        "August in Fès is hot but the ancient medina comes alive in the evenings. The world's oldest university town and labyrinthine souks are a sensory feast.",
      highlights: ["Chouara Tannery", "Al Quaraouiyine University", "Fès el-Bali Medina"],
      avgTempCelsius: 36,
      bestFor: "Culture & History",
      imageEmoji: "🧵",
      iataCode: "FEZ",
    },
    // India
    {
      id: "spiti-aug",
      name: "Spiti Valley (Peak)",
      country: "India",
      region: "India",
      description:
        "August is the heart of Spiti's brief summer window. Chandratal Lake reflects the sky like a mirror, Pin Valley blooms with rare Himalayan flowers, and roads are open.",
      highlights: ["Chandratal Lake Camp", "Pin Valley National Park", "Kibber Village"],
      avgTempCelsius: 12,
      bestFor: "High-Altitude Adventure",
      imageEmoji: "🌊",
      iataCode: "KUU",
    },
    {
      id: "leh-aug",
      name: "Leh-Ladakh (Peak)",
      country: "India",
      region: "India",
      description:
        "August is Ladakh's peak season with all mountain passes open. The Hemis Festival features colorful masked dances in Ladakh's largest monastery.",
      highlights: ["Hemis Festival", "Zanskar River Rafting", "Tso Moriri Lake"],
      avgTempCelsius: 17,
      bestFor: "Festivals & Mountain Adventure",
      imageEmoji: "🎭",
      iataCode: "IXL",
    },
    {
      id: "hampi-aug",
      name: "Hampi (Monsoon)",
      country: "India",
      region: "India",
      description:
        "August rains transform Hampi's boulder landscape into a dramatic canvas. The Tungabhadra River swells, boulders glisten, and the ruins look hauntingly beautiful.",
      highlights: ["Tungabhadra Dam Backwaters", "Lotus Mahal", "Hemakuta Hill Temples"],
      avgTempCelsius: 27,
      bestFor: "Heritage & Monsoon Photography",
      imageEmoji: "🌦️",
      iataCode: "HBX",
    },
  ],

  9: [
    // Global
    {
      id: "italy-sep",
      name: "Tuscany",
      country: "Italy",
      region: "Global",
      description:
        "September is harvest season in Tuscany. Vineyards turn gold and amber, truffle hunting begins, and the summer crowds have thinned. Perfect for agriturismo stays.",
      highlights: ["Chianti Wine Harvest Tour", "San Gimignano Towers", "Truffle Hunting in Alba"],
      avgTempCelsius: 22,
      bestFor: "Wine & Countryside",
      imageEmoji: "🍷",
      iataCode: "FLR",
    },
    {
      id: "portugal-sep",
      name: "Algarve",
      country: "Portugal",
      region: "Global",
      description:
        "September in the Algarve is arguably better than peak summer — warm seas, golden cliffs, fewer tourists, and lower prices. Beach hopping is superb.",
      highlights: ["Benagil Sea Cave", "Praia da Marinha", "Cape St. Vincent Lighthouse"],
      avgTempCelsius: 24,
      bestFor: "Beaches & Cliffs",
      imageEmoji: "🌊",
      iataCode: "FAO",
    },
    {
      id: "turkey-sep",
      name: "Cappadocia",
      country: "Turkey",
      region: "Global",
      description:
        "September is ideal for Cappadocia — hot air balloons drift over fairy chimneys in crisp morning air, underground cities are cool to explore, and crowds thin.",
      highlights: ["Hot Air Balloon Sunrise", "Göreme Open Air Museum", "Underground City of Derinkuyu"],
      avgTempCelsius: 20,
      bestFor: "Unique Landscapes & Culture",
      imageEmoji: "🎈",
      iataCode: "ASR",
    },
    // India
    {
      id: "rajasthan-sep",
      name: "Rajasthan",
      country: "India",
      region: "India",
      description:
        "September marks the end of monsoon in Rajasthan. Forts and lakes are surrounded by lush greenery — a dramatic contrast to the desert's golden hues.",
      highlights: ["Ranthambore Tiger Safari", "Chittorgarh Fort", "Pushkar Lake"],
      avgTempCelsius: 29,
      bestFor: "Forts & Wildlife",
      imageEmoji: "🐅",
      iataCode: "JAI",
    },
    {
      id: "goa-sep",
      name: "Goa (Pre-Season)",
      country: "India",
      region: "India",
      description:
        "September is Goa's secret best time — the monsoon is retreating, waterfalls still roar, the sea turns blue-green, and prices are a third of peak season.",
      highlights: ["Dudhsagar Falls in Full Flow", "Spice Plantation Tours", "Quiet South Goa Beaches"],
      avgTempCelsius: 27,
      bestFor: "Budget Travel & Waterfalls",
      imageEmoji: "💦",
      iataCode: "GOI",
    },
    {
      id: "kerala-sep",
      name: "Kerala (Onam)",
      country: "India",
      region: "India",
      description:
        "September brings Onam, Kerala's grandest harvest festival. Spectacular snake boat races on the Pampa River and elaborate flower carpets (Pookalam) adorn every household.",
      highlights: ["Nehru Trophy Boat Race", "Onam Sadya (Feast)", "Thrissur Pooram"],
      avgTempCelsius: 26,
      bestFor: "Festivals & Culture",
      imageEmoji: "🚣",
      iataCode: "COK",
    },
  ],

  10: [
    // Global
    {
      id: "japan-oct",
      name: "Tokyo (Autumn)",
      country: "Japan",
      region: "Global",
      description:
        "October brings Japan's spectacular autumn foliage season. Nikko's temples flame with reds and golds, Mount Fuji is freshly snow-capped, and Tokyo's parks are glorious.",
      highlights: ["Nikko Toshogu Shrine", "Mount Fuji Views", "Shinjuku Gyoen Autumn Colors"],
      avgTempCelsius: 17,
      bestFor: "Autumn Foliage & Culture",
      imageEmoji: "🍁",
      iataCode: "NRT",
    },
    {
      id: "thailand-oct",
      name: "Koh Samui",
      country: "Thailand",
      region: "Global",
      description:
        "October transitions to dry season in Koh Samui. Emerald sea caves, luxury resorts, and Full Moon Party preparations make the Gulf coast irresistible.",
      highlights: ["Ang Thong Marine Park", "Full Moon Party on Koh Phangan", "Koh Nang Yuan Snorkeling"],
      avgTempCelsius: 27,
      bestFor: "Islands & Nightlife",
      imageEmoji: "🌙",
      iataCode: "USM",
    },
    {
      id: "bali-oct",
      name: "Ubud",
      country: "Indonesia",
      region: "Global",
      description:
        "October is the sweet spot for Bali — the dry season lingers, rice terraces are lush, and Ubud's arts scene, yoga retreats, and cooking classes are at their best.",
      highlights: ["Tegallalang Rice Terraces", "Ubud Monkey Forest", "Traditional Kecak Dance"],
      avgTempCelsius: 26,
      bestFor: "Wellness & Culture",
      imageEmoji: "🧘",
      iataCode: "DPS",
    },
    // India
    {
      id: "kullu-oct",
      name: "Kullu (Dussehra)",
      country: "India",
      region: "India",
      description:
        "October's Kullu Dussehra is unique — 365 deities are carried in palanquins to the Dhalpur Maidan in a week-long international fair. A spectacle unlike anywhere else.",
      highlights: ["International Dussehra Fair", "Bijli Mahadev Temple", "Great Himalayan National Park"],
      avgTempCelsius: 14,
      bestFor: "Festivals & Mountains",
      imageEmoji: "🪔",
      iataCode: "KUU",
    },
    {
      id: "mysore-oct",
      name: "Mysuru (Dasara)",
      country: "India",
      region: "India",
      description:
        "Mysuru Dasara is Karnataka's greatest spectacle — the Mysore Palace is lit with 100,000 bulbs, a golden elephant procession fills the streets, and the city dances.",
      highlights: ["Mysore Palace Illumination", "Jumbo Savari Elephant Procession", "Chamundi Hills"],
      avgTempCelsius: 25,
      bestFor: "Grand Festivals & Heritage",
      imageEmoji: "🐘",
      iataCode: "MYQ",
    },
    {
      id: "coorg-oct",
      name: "Coorg (Post-Monsoon)",
      country: "India",
      region: "India",
      description:
        "October is Coorg's reward after monsoon — pristine waterfalls, coffee harvest begins, the air smells of spices, and the hills are an impossibly deep green.",
      highlights: ["Coffee Harvest Experience", "Nagarhole Tiger Reserve", "Mandalpatti View Point"],
      avgTempCelsius: 22,
      bestFor: "Coffee & Wildlife",
      imageEmoji: "🌿",
      iataCode: "IXM",
    },
  ],

  11: [
    // Global
    {
      id: "maldives-nov",
      name: "North Malé Atoll",
      country: "Maldives",
      region: "Global",
      description:
        "November marks the start of Maldives' dry season. Manta rays begin aggregating around Hanifaru Bay and the sea visibility is exceptional for diving.",
      highlights: ["Manta Ray Snorkeling", "Bioluminescent Beach", "Submarine Sandbank Picnic"],
      avgTempCelsius: 28,
      bestFor: "Diving & Marine Life",
      imageEmoji: "🦈",
      iataCode: "MLE",
    },
    {
      id: "egypt-nov",
      name: "Luxor",
      country: "Egypt",
      region: "Global",
      description:
        "November is perfect for Egypt — comfortable temperatures and clear skies for hot air balloon rides over the Valley of the Kings at sunrise.",
      highlights: ["Valley of the Kings", "Hot Air Balloon over Luxor", "Karnak Temple Complex"],
      avgTempCelsius: 25,
      bestFor: "Ancient History & Archaeology",
      imageEmoji: "🏺",
      iataCode: "LXR",
    },
    {
      id: "australia-nov",
      name: "Great Barrier Reef",
      country: "Australia",
      region: "Global",
      description:
        "November starts Queensland's dive season. The Great Barrier Reef's visibility peaks before summer jellyfish season, making it perfect for snorkeling and live-aboard diving.",
      highlights: ["Outer Reef Snorkeling", "Whitsunday Islands Sailing", "Daintree Rainforest"],
      avgTempCelsius: 26,
      bestFor: "Diving & Reef",
      imageEmoji: "🐠",
      iataCode: "CNS",
    },
    // India
    {
      id: "pushkar-nov",
      name: "Pushkar",
      country: "India",
      region: "India",
      description:
        "November's Pushkar Camel Fair is one of the world's most extraordinary spectacles — 50,000 camels, performers, holy men, and traders converge on the Thar Desert.",
      highlights: ["Pushkar Camel Fair", "Brahma Temple", "Pushkar Lake Sunset"],
      avgTempCelsius: 22,
      bestFor: "Festivals & Desert Culture",
      imageEmoji: "🐪",
      iataCode: "JAI",
    },
    {
      id: "goa-nov",
      name: "Goa (Season Opens)",
      country: "India",
      region: "India",
      description:
        "November is when Goa truly wakes up — the shacks open, trance parties begin, the sea is perfect, and the whole state smells of sunscreen and cashew feni.",
      highlights: ["Sunburn Music Festival", "North Goa Flea Markets", "Goa Heritage Festival"],
      avgTempCelsius: 27,
      bestFor: "Festivals & Beach Party",
      imageEmoji: "🎵",
      iataCode: "GOI",
    },
    {
      id: "pondicherry-nov",
      name: "Pondicherry",
      country: "India",
      region: "India",
      description:
        "November is ideal for Pondicherry — the Bay of Bengal is calm, the French Quarter's cafes are buzzing, and Auroville's spiritual ambience is at its most inviting.",
      highlights: ["French Quarter Cycling", "Auroville Matrimandir", "Promenade Beach Sunrise"],
      avgTempCelsius: 26,
      bestFor: "Heritage & Spirituality",
      imageEmoji: "🌅",
      iataCode: "PNY",
    },
  ],

  12: [
    // Global
    {
      id: "switzerland-dec",
      name: "Zermatt",
      country: "Switzerland",
      region: "Global",
      description:
        "December transforms Zermatt into a fairy-tale Christmas village. Car-free streets, the Matterhorn dusted in snow, and world-class skiing make it magical.",
      highlights: ["Matterhorn Views", "Klein Matterhorn Skiing", "Christmas Markets"],
      avgTempCelsius: -2,
      bestFor: "Skiing & Christmas Markets",
      imageEmoji: "⛄",
      iataCode: "ZRH",
    },
    {
      id: "newyork-dec",
      name: "New York City",
      country: "United States",
      region: "Global",
      description:
        "December in New York is iconic — Rockefeller Center tree, ice skating in Central Park, holiday window displays, and Times Square New Year's Eve.",
      highlights: ["Rockefeller Center Tree", "Central Park Ice Skating", "Times Square New Year's Eve"],
      avgTempCelsius: 3,
      bestFor: "Christmas & New Year",
      imageEmoji: "🗽",
      iataCode: "JFK",
    },
    {
      id: "australia-dec",
      name: "Sydney",
      country: "Australia",
      region: "Global",
      description:
        "December is summer in Sydney. Bondi Beach is packed, the Opera House hosts outdoor concerts, and the New Year's Eve fireworks over the harbour are world-famous.",
      highlights: ["Bondi Beach BBQ", "Sydney Opera House", "New Year's Harbour Fireworks"],
      avgTempCelsius: 23,
      bestFor: "Summer Beach & New Year",
      imageEmoji: "🎆",
      iataCode: "SYD",
    },
    // India
    {
      id: "goa-dec",
      name: "Goa (Christmas)",
      country: "India",
      region: "India",
      description:
        "December is Goa's crown jewel month — Christmas illuminates Old Goa's churches, midnight masses draw thousands, and New Year parties on the beach are legendary.",
      highlights: ["Old Goa Midnight Mass", "New Year's Eve Beach Party", "Carnival Preparations"],
      avgTempCelsius: 24,
      bestFor: "Christmas & New Year Celebrations",
      imageEmoji: "🎄",
      iataCode: "GOI",
    },
    {
      id: "rann-dec",
      name: "Rann of Kutch",
      country: "India",
      region: "India",
      description:
        "December is peak season for the Rann Utsav. The vast white salt desert under a full moon is ethereal, and the festival showcases Kutchi crafts, music, and camel rides.",
      highlights: ["Rann Utsav Festival", "Full Moon Night on Salt Desert", "Dholavira Ruins"],
      avgTempCelsius: 17,
      bestFor: "Desert Festival & Crafts",
      imageEmoji: "🌕",
      iataCode: "BHJ",
    },
    {
      id: "auli-dec",
      name: "Auli",
      country: "India",
      region: "India",
      description:
        "December brings fresh powder snow to Auli, Uttarakhand's premier ski resort. Views of Nanda Devi and the Garhwal Himalayas from ski slopes are extraordinary.",
      highlights: ["Skiing on Nanda Devi Slopes", "Gorson Bugyal Trek", "Joshimath Ropeway"],
      avgTempCelsius: -2,
      bestFor: "Skiing & Himalayan Views",
      imageEmoji: "🎿",
      iataCode: "DED",
    },
  ],
};
